### PR TITLE
Release/0.7.0rc1

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Not sure if we want to pull in perses as a dep?

**Comment by richardjgowers** [comment]
Probably not this release

**Comment by mikemhenry** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=687397&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=907
@richardjgowers looks like it is working!

**Comment by mikemhenry** [comment]
Ah it works because we are using [`git_rev`](https://github.com/conda-forge/openfe-feedstock/pull/16/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR10)

**Comment by mikemhenry** [comment]
We don't need this anymore but this is how we can do an RC

**Pull request closed without merging**
