### PR TITLE
openfe release v1.2.0

### PR DESCRIPTION
**Pull request by atravitz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by atravitz** [comment]
@conda-forge-admin, please rerender

**Review by IAlibay — CHANGES_REQUESTED** [review]
Could you:

- Bump up the minimum python version to 3.10
- Unpin matplotlib-base (the issue was fixed in the last release)

**Comment by atravitz** [comment]
> Could you:
> 
>     * Bump up the minimum python version to 3.10
> 
>     * Unpin matplotlib-base (the issue was fixed in the last release)

done. which change makes us require 3.10?

**Comment by IAlibay** [comment]
> > Could you:
> > ```
> > * Bump up the minimum python version to 3.10
> > 
> > * Unpin matplotlib-base (the issue was fixed in the last release)
> > ```
> 
> done. which change makes us require 3.10?

This: https://github.com/OpenFreeEnergy/openfe/blob/main/pyproject.toml#L25

**Review by IAlibay — APPROVED** [review]
Just waiting on the gufe feedstock update.

**Comment by mikemhenry** [comment]
Just merged that in, so it should be ready soon ™️

**Review by mikemhenry — CHANGES_REQUESTED** [review]
In the run section we need python >= 3.10

**Pull request merged**
